/**
 * SEO helpers — one place that decides how every page's <title>, description,
 * canonical URL, robots directives, social-preview tags and JSON-LD are built.
 * Used by the `metadata` exports in each src/app/.../page.jsx.
 */
import { CLINIC, SITE_URL } from '@/config';

export const SITE_NAME = CLINIC.shortName; // "Dr. Dhananjayas Clinic"

/* Stable @id anchors so every JSON-LD block on the site points at the same entities */
export const CLINIC_ID = `${SITE_URL}/#clinic`;
export const WEBSITE_ID = `${SITE_URL}/#website`;

/* Home page copy — keyword-first title, ≤160-character description */
export const HOME_TITLE = 'Ayurvedic Piles, Fistula & Fissure Hospital in Porur, Chennai | Dr. Dhananjayas';
export const HOME_DESCRIPTION =
  'Ayurvedic care for piles, fistula and fissure with Dr. Venkhatesan at Dr. Dhananjayas Hospitals, Porur, Chennai. Authentic Kshara Sutra, no major operations.';

/** Indexable-page robots directives (large image previews help Discover / image results). */
export const ROBOTS_INDEX = {
  index: true,
  follow: true,
  googleBot: {
    index: true,
    follow: true,
    'max-image-preview': 'large',
    'max-snippet': -1,
    'max-video-preview': -1,
  },
};

/** Search-console ownership tags, only emitted when the env vars are set. */
export function siteVerification() {
  const google = process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION;
  const bing = process.env.NEXT_PUBLIC_BING_SITE_VERIFICATION;
  const v = {};
  if (google) v.google = google;
  if (bing) v.other = { 'msvalidate.01': bing };
  return Object.keys(v).length ? v : undefined;
}

/** Route path → canonical path. Trailing slash matches `trailingSlash: true` in next.config.mjs. */
export function canonicalPath(path) {
  if (!path || path === '/') return '/';
  return `${path.replace(/\/+$/, '')}/`;
}

/** Absolute URL of a route ("/about-us" → "https://…/about-us/"). */
export function absoluteUrl(path) {
  return `${SITE_URL}${canonicalPath(path)}`;
}

/** Absolute URL of a static asset ("/og/home.jpg" → "https://…/og/home.jpg"). */
export function assetUrl(path) {
  return `${SITE_URL}${path}`;
}

/** 1200×630 social card generated by scripts/optimize-images.mjs → public/og/<slug>.jpg */
export function ogCard(slug, alt) {
  return { url: `/og/${slug}.jpg`, width: 1200, height: 630, alt };
}

export const DEFAULT_OG_IMAGE = ogCard(
  'home',
  'Patient consulting a doctor about piles treatment at Dr. Dhananjayas Hospitals, Porur'
);

/** Serialise JSON-LD safely for a <script> tag (never lets "</script>" through). */
export function safeJsonLd(data) {
  return JSON.stringify(data).replace(/</g, '\\u003c');
}

/** schema.org BreadcrumbList for [{ name, path }, …] (first item should be Home). */
export function breadcrumbJsonLd(items) {
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: items.map((it, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      name: it.name,
      item: absoluteUrl(it.path),
    })),
  };
}

/**
 * Build the Next.js `metadata` object for one page.
 *
 * @param {object} o
 * @param {string} [o.title]          Page title; root layout appends " | Dr. Dhananjayas Clinic".
 * @param {string} [o.absoluteTitle]  Use instead of `title` to bypass the template (home page).
 * @param {string}  o.description     ≤160 chars, unique per page.
 * @param {string}  o.path            Route path, e.g. "/about-us".
 * @param {object} [o.image]          { url, width, height, alt } — relative URLs resolve via metadataBase.
 * @param {string} [o.ogTitle]        Social-card title override.
 * @param {string} [o.ogDescription]  Social-card description override.
 */
export function pageMetadata({
  title,
  absoluteTitle,
  description,
  path,
  image = DEFAULT_OG_IMAGE,
  ogTitle,
  ogDescription,
}) {
  const fullTitle = absoluteTitle || `${title} | ${SITE_NAME}`;
  const url = canonicalPath(path);

  return {
    title: absoluteTitle ? { absolute: absoluteTitle } : title,
    description,
    alternates: { canonical: url },
    robots: ROBOTS_INDEX,
    openGraph: {
      type: 'website',
      locale: 'en_IN',
      siteName: SITE_NAME,
      url,
      title: ogTitle || fullTitle,
      description: ogDescription || description,
      images: [image],
    },
    twitter: {
      card: 'summary_large_image',
      title: ogTitle || fullTitle,
      description: ogDescription || description,
      images: [image.url],
    },
  };
}
